name: Kustomize Build Action

on:
  workflow_dispatch:

jobs:
  Kustomize-Build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Kustomize build
        # uses: kevinobee/kustomize-build-action@v1
        uses: ./action.yml
        with:
          build-path: '.'
          output-file: 'kustomize.yaml'
          upload-artifact-name: 'kustomize'

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
